import { useEffect,useState,type FormEvent } from 'react';
import { Link,useParams } from 'react-router-dom';
import { api } from '../lib/api'; import type { Contact,SponsorDetail as Detail,Tier } from '../lib/admin'; import { errorMessage } from '../lib/admin'; import { Field,Select } from './Sponsors';
export default function SponsorDetail(){const{id}=useParams();const[data,setData]=useState<Detail|null>(null);const[tiers,setTiers]=useState<Tier[]>([]);const[error,setError]=useState('');const[newContact,setNewContact]=useState({email:'',fullName:'',title:'',role:'viewer'});const[logoStatus,setLogoStatus]=useState<'idle'|'uploading'|'saved'>('idle');
  async function load(){try{const[d,t]=await Promise.all([api.get<Detail>(`/admin/sponsors/${id}`),api.get<Tier[]>('/admin/tiers')]);setData(d);setTiers(t)}catch(e){setError(errorMessage(e))}} useEffect(()=>{Promise.all([api.get<Detail>(`/admin/sponsors/${id}`),api.get<Tier[]>('/admin/tiers')]).then(([d,t])=>{setData(d);setTiers(t)}).catch(e=>setError(errorMessage(e)))},[id]);
  async function saveSponsor(e:FormEvent){e.preventDefault();if(!data)return;try{await api.patch(`/admin/sponsors/${id}`,data.sponsor);await load()}catch(x){setError(errorMessage(x))}}
  async function add(e:FormEvent){e.preventDefault();try{await api.post(`/admin/sponsors/${id}/contacts`,newContact);setNewContact({email:'',fullName:'',title:'',role:'viewer'});await load()}catch(x){setError(errorMessage(x))}}
  async function saveContact(c:Contact){try{await api.patch(`/admin/sponsors/${id}/contacts/${c.id}`,c);await load()}catch(x){setError(errorMessage(x))}}
  async function uploadLogo(file:File){setError('');setLogoStatus('uploading');try{await api.upload(`/admin/sponsors/${id}/logo`,'file',file);setLogoStatus('saved')}catch(x){setLogoStatus('idle');setError(errorMessage(x))}}
  async function clearLogo(){setError('');setLogoStatus('uploading');try{await api.delete(`/admin/sponsors/${id}/logo`);setLogoStatus('idle')}catch(x){setLogoStatus('idle');setError(errorMessage(x))}}
  if(!data)return <div className="wrap"><p>{error||'Loading…'}</p></div>; const s=data.sponsor; const set=(patch:Partial<typeof s>)=>setData({...data,sponsor:{...s,...patch}});
  return <div className="wrap"><Link className="link" to="/sponsors">← Sponsors</Link><div className="page-head"><h1>{s.name}</h1></div>{error&&<div className="note note-error">{error}</div>}<form className="card form-grid" onSubmit={saveSponsor}><Field label="Company name" value={s.name} onChange={name=>set({name})}/><Field label="Slug" value={s.slug} onChange={slug=>set({slug})}/><Field label="Brand hex" value={s.brandHex||''} required={false} onChange={brandHex=>set({brandHex:brandHex.toUpperCase()})}/><Field label="Website" value={s.websiteUrl||''} required={false} onChange={websiteUrl=>set({websiteUrl})}/><Select label="Tier" value={s.tierId||''} onChange={tierId=>set({tierId:tierId||null})}><option value="">No tier</option>{tiers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select><Select label="Status" value={s.status} onChange={status=>set({status:status as typeof s.status})}><option value="prospective">Prospective</option><option value="active">Active</option><option value="lapsed">Lapsed</option></Select><div className="form-actions"><button className="btn btn-primary">Save sponsor</button></div></form><h2 className="section-title">Logo</h2><div className="card"><p className="muted" style={{marginTop:0,fontSize:14}}>PNG, JPEG, WebP, or SVG. 1 MB max. Overwrites the current logo.</p><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" disabled={logoStatus==='uploading'} onChange={e=>{const f=e.target.files?.[0];if(f)uploadLogo(f);e.target.value='';}}/><button type="button" className="btn btn-secondary btn-sm" style={{marginLeft:12}} disabled={logoStatus==='uploading'} onClick={clearLogo}>Remove logo</button>{logoStatus==='uploading'&&<span className="muted" style={{marginLeft:12}}>Uploading…</span>}{logoStatus==='saved'&&<span className="muted" style={{marginLeft:12}}>Saved.</span>}</div><h2 className="section-title">Contacts</h2>{data.contacts.map(c=><ContactRow key={c.id} contact={c} save={saveContact}/>)}<form className="card form-grid" onSubmit={add}><Field label="Email" type="email" value={newContact.email} onChange={email=>setNewContact({...newContact,email})}/><Field label="Full name" value={newContact.fullName} onChange={fullName=>setNewContact({...newContact,fullName})}/><Field label="Title" value={newContact.title} required={false} onChange={title=>setNewContact({...newContact,title})}/><Select label="Role" value={newContact.role} onChange={role=>setNewContact({...newContact,role})}><option value="primary">Primary</option><option value="billing">Billing</option><option value="viewer">Viewer</option></Select><div className="form-actions"><button className="btn btn-primary">Invite contact</button></div></form></div>}
function ContactRow({contact,save}:{contact:Contact,save:(c:Contact)=>void}){const[c,setC]=useState(contact);return <div className="card contact-row"><input className="input" value={c.email} onChange={e=>setC({...c,email:e.target.value})}/><input className="input" value={c.fullName||''} onChange={e=>setC({...c,fullName:e.target.value})}/><input className="input" value={c.title||''} onChange={e=>setC({...c,title:e.target.value})}/><select className="input" value={c.role} onChange={e=>setC({...c,role:e.target.value as Contact['role']})}><option value="primary">Primary</option><option value="billing">Billing</option><option value="viewer">Viewer</option></select><span className="muted">{c.activated?'Signed in':'Invited'}</span><button type="button" className="btn btn-secondary btn-sm" onClick={()=>save(c)}>Save</button></div>}
